title: Dr. Michael Rushanan
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website of Dr. Mike Rushanan. It holds his CV, links
  his research papers, and maintains his technical blog entries. His entries
  cover computer security, networking, embedded systems, IoT, software
  development, and more. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michaelrushanan.org" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mike Rushanan # add your name
author-img: mike-rushanan-bitmoji.png # add your photo
about-author: I am a computer security researcher, programmer, and tinkerer. I contribute to open source development in my free time, and I secure medical devices in my paid time.
social-twitter: micharu123 # add your Twitter handle
social-facebook: michael.rushanan # add your Facebook handle
social-github: micharu123 # add your Github handle
social-linkedin: michael-rushanan-8a1a8126 # add your Linkedin handle
social-email: micharu123~@~gmail.com # add your Email address

# Disqus
discus-identifier: micharu123 # add your discus identifier

# Tracker
analytics: G-JC6V8LBGSG # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
